#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PokemonApp.Resource", IsApplication=true)]

namespace PokemonApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::PokemonApp.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int theme_custom_background = 2130771968;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int icon_pikachu = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int icon_pokedex = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int icon_superball = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int image_not_found = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int pokemon_arbok = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int pokemon_beedrill = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int pokemon_blastoise = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int pokemon_bulbasaur = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int pokemon_butterfree = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int pokemon_caterpie = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int pokemon_charizard = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int pokemon_charmander = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int pokemon_charmeleon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int pokemon_clefable = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int pokemon_clefairy = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int pokemon_diglett = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int pokemon_ekans = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int pokemon_fearow = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int pokemon_gloom = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int pokemon_golbat = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int pokemon_ivysaur = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int pokemon_jigglypuff = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int pokemon_kakuna = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int pokemon_metapod = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int pokemon_nidoking = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int pokemon_nidoqueen = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int pokemon_nidoran_female = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int pokemon_nidoran_male = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int pokemon_nidorina = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int pokemon_nidorino = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int pokemon_ninetales = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int pokemon_oddish = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int pokemon_paras = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int pokemon_parasect = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int pokemon_pidgeot = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int pokemon_pidgeotto = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int pokemon_pidgey = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int pokemon_pikachu = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int pokemon_raichu = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int pokemon_raticate = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int pokemon_rattata = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int pokemon_sandshrew = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int pokemon_sandslash = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int pokemon_spearow = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int pokemon_squirtle = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int pokemon_venomoth = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int pokemon_venonat = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int pokemon_venusaur = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int pokemon_vileplume = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int pokemon_vulpix = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int pokemon_wartortle = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int pokemon_weedle = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int pokemon_wigglytuff = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int pokemon_zubat = 2130837558;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int checkbox = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int gridview = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int pokemonIcon = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int pokemonName = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int pokemon_height = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int pokemon_height_label = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int pokemon_id = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int pokemon_id_label = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int pokemon_item_image = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int pokemon_item_name = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int pokemon_type = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int pokemon_type_label = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int pokemon_weight = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int pokemon_weight_label = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int searchview = 2130903054;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int GridViewLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int HomeScreenLayout = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int PokemonDetailsLayout = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int ViewPokemonLayout = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7F050000
			public const int LoadingMessage = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ProgressHeaderMessage = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
